### ISSUE TITLE
Unify headers for interscript index page and JS demo pages

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript.org#24]
Now that we have a unified site, we should also unify the header.

Index page:
<img width="857" alt="Screenshot 2021-06-02 at 10 24 26 AM" src="https://user-images.githubusercontent.com/11865/120414562-c00f5480-c38c-11eb-9f63-d1c4753e7835.png">

JS demo page:
<img width="961" alt="Screenshot 2021-06-02 at 10 24 56 AM" src="https://user-images.githubusercontent.com/11865/120414605-d1f0f780-c38c-11eb-93d5-01f7e1966dd2.png">

We should also directly copy out this content from the Interscript repo README directly into this repository, so that this repository is authoritative for content.

Proposed information hierarchy:

* Home
  * Introduction
  * Demonstration
  * Statistics
* Featured authorities
  * UN
  * BGN/PCGN
  * ALA-LC
  * ODNI
  * OGC
* Try: API
* Try: JavaScript
* Systems (index of all systems)
  * Individual system (show details about a single system, provides system definition references)
* Integration (Ruby, JS)
  * Installation
  * Usage
  * Ruby/JS documentation
* Customising and Contributing
  * Map editing guide
* About
  * Partners
* View on GitHub

**Comment by webdev778** [comment]
#42
