### ISSUE TITLE
Add "About" page

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript.org#35]
Interscript has been supported by:

* Professor Lyubomir Ivanov (Bulgarian Academy of Sciences)
* BGN https://www.usgs.gov/core-science-systems/ngp/board-on-geographic-names
* OGC https://www.ogc.org
* CalConnect https://www.calconnect.org
* UNGEGN (https://unstats.un.org/unsd/ungegn/) Working Group on Romanization Systems (http://www.eki.ee/wgrs/)

**Comment by webdev778** [comment]
#42
