### ISSUE TITLE
Safari Styling 

### ISSUE THREAD

**Issue by webdev778** [interscript/interscript.org#36]
System Chart styling breaking on safari as following. 
Need to make sure all styling working peroperly on safari
![image](https://user-images.githubusercontent.com/28761746/123746683-8d517100-d8e4-11eb-85a2-0581f0588b03.png)
![image](https://user-images.githubusercontent.com/28761746/123746705-95a9ac00-d8e4-11eb-85d6-c400f133b9b8.png)

**Comment by webdev778** [comment]
Fixed with PR #50 

![image](https://user-images.githubusercontent.com/28761746/125316909-26639b80-e36b-11eb-9291-b91aab1a2cc1.png)

**Comment by ronaldtse** [comment]
Thanks @webdev778 !
