### ISSUE TITLE
Make metadata/title consistent on Systems page

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript.org#45]
https://www.interscript.org/systems

We need a consistent naming scheme.

<img width="942" alt="Screenshot 2021-07-10 at 12 20 29 AM" src="https://user-images.githubusercontent.com/11865/125108505-b2c85100-e114-11eb-9bbe-6ea505f0b4a4.png">

**Comment by ronaldtse** [comment]
@webdev778 in https://github.com/interscript/maps/commit/ef7176ba39626735394617b215099a618b6a5551 I have made most of the names consistent. Can you trigger a re-deploy of the site with the new names? Thanks.

**Comment by webdev778** [comment]
Sure, I'll
