### ISSUE TITLE
`stategeocadastre-ukr-Cyrl-Latn-1993` system not working on interscript.org

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript.org#49]
<img width="914" alt="Screenshot 2021-07-12 at 4 41 06 PM" src="https://user-images.githubusercontent.com/11865/125258238-bc2e0500-e330-11eb-921b-dff95b565bc0.png">

System: `stategeocadastre-ukr-Cyrl-Latn-1993`

**Comment by webdev778** [comment]
API or javascript ?

**Comment by ronaldtse** [comment]
Javascript.

**Comment by webdev778** [comment]
got it, I'll check

**Comment by webdev778** [comment]
Fixed

![image](https://user-images.githubusercontent.com/28761746/126881548-5931da94-5241-4e23-a03a-9895a71f9fb2.png)
