### ISSUE TITLE
Fetch the necessary artifacts on deployment time.

### ISSUE THREAD

**Issue by webdev778** [interscript/interscript.org#51]
276 map javascript files and json files are currently included in this repository, as outcome from [Interscript ](https://github.com/interscript/interscript)repo.

JSON files is used for System Chart.

Definitely, it's causing the repo heavy and so makes git manipulation slow.
I'm proposing Update the GHA to include those files when necessary (Only Deployment).

- Get rid of those files from the repo
- Fetch those files on GHA

For development environment, we will have a way to fetch those files automatically.

**Comment by ronaldtse** [comment]
Sure, we really don't want to keep generated artifacts inside the Git repo.

**Comment by webdev778** [comment]
Declined the #PR 52 and go with using Upload/Download GHA as @ronaldtse recommended.

**Comment by webdev778** [comment]
Closed with PR #54
