### ISSUE TITLE
Add functionality to "detect the transliteration system used" for a phrase

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript.org#55]
We should have a page that allows user to enter a transliterated phrase, and we return a list of transliteration systems that produce close matches (probably scored by edit distance).

This depends on https://github.com/interscript/interscript/issues/728.

**Comment by webdev778** [comment]
CORS issue blocking me to call api from live site and local 

"https://www.interscript.org" and "http://localhost:3000" need be in whitelist (allowed_origins)
pint @ronaldtse @phuonghuynh

**Comment by phuonghuynh** [comment]
Checking it

**Comment by webdev778** [comment]
#63
