### ISSUE TITLE
Blog post date not as authored date

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript.org#60]
<img width="631" alt="Screenshot 2021-08-11 at 3 36 52 PM" src="https://user-images.githubusercontent.com/11865/128988980-5f974961-46a7-4222-b299-52e9f9c06d93.png">

The blog posts display whatever is the last deployed date. 

We should support post metadata, e.g. in Metanorma:
https://raw.githubusercontent.com/metanorma/metanorma.org/main/_posts/2021-07-20-metanorma-with-proxies.adoc

```adoc
---
layout: post
title:  "Using Metanorma with proxies (HTTPS, SOCKS)"
date:   2021-07-20
categories: documentation
author:
  name: Alexander Bobrikovich
  email: abobrikovich@gmail.com
  social_links:
    - https://github.com/camobap
excerpt: >-
  Metanorma now supports Internet access via HTTP/HTTPS and SOCKS proxy servers!
---

== Introduction

A good portion of Metanorma users work in security-sensitive environments (to no
one's surprise? :-) ) that have firewalls that block access to the Internet.
```

**Comment by webdev778** [comment]
the current version of metadata's format is 
```
= Diacritization in Arabic with Deep Learning
Jair Wuilloud
v1.0, 2021-08-03
:doctype: book
:docinfo:
```
within this PR #73 

The suggested format is not working for adoc => html since it's markdown format and it doesn't have regular structure to analyse.
Working with metanorma, there must be a better solution for this.

**Comment by webdev778** [comment]
The mentioned format is JeckyII format. not compatible with adoc

**Comment by webdev778** [comment]
I would take the approach like

```
step 0. split an .adoc file by ---, parse first part as yaml, second part as adoc
step 1. adoc -> html, yaml -> json (or js object)
step 2. analyse the yaml and html separately
```
