### ISSUE TITLE
Homepage should no longer read from README, separate it out as an individual page

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript.org#71]
The front page would just describe some introduction, some stats and link to the various pages.

**Comment by ronaldtse** [comment]
Is this completed?

**Comment by ronaldtse** [comment]
Ping @webdev778

**Comment by ronaldtse** [comment]
Page is broken right now, need to remove the .gif anyway. 

<img width="541" alt="Screenshot 2021-11-22 at 9 48 22 PM" src="https://user-images.githubusercontent.com/11865/142872778-98bb8d54-4e14-4904-a602-f62fcd0cda96.png">

**Comment by webdev778** [comment]
Fixed

**Comment by ronaldtse** [comment]
Confirmed.
