### ISSUE TITLE
Allow using Arabic diacriticization stage before Arabic script conversion

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript.org#72]
Arabic script conversion generally requires two stages:
1. Apply Arabic diacriticization
2. Run the Arabic script conversion system

We should enable this on https://www.interscript.org/try-api . Perhaps a checkbox can be added to "Diacriticize Arabic" that will run the pipeline of "diacriticize Arabic => run selected Arabic conversion system"

**Comment by webdev778** [comment]
We will then have to hit api with: "var-ara-Arab-Arab-rababa|bgnpcgn-ara-current-system-name" as a map name. Then in reverse we would hit it with "bgnpcgn-ara-current-system-name-reverse-name|var-ara-Arab-Arab-rababa-reverse"

**Comment by ronaldtse** [comment]
Sounds good!
