### ISSUE TITLE
400 bad request for Rababa

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript.org#87]
@phuonghuynh @webdev778 can you help check what's going on? We need to fix this ASAP. Thanks!

<img width="927" alt="Screenshot 2022-06-29 at 10 28 25 AM" src="https://user-images.githubusercontent.com/11865/176331519-e4257479-fca6-4861-ae2d-4209860734ae.png">

**Comment by webdev778** [comment]
This got fixed by https://github.com/interscript/maps/commit/6d5f69f54065582fe52485777b5659547af3cd6c but the Gem hasn't been released before.
